version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "monthly"
      open-pull-requests-limit: 10
      groups:
          production-dependencies:
              dependency-type: "production"
              update-types:
                  - "patch"
          development-dependencies:
              dependency-type: "development"
              update-types:
                  - "patch"
                  - "minor"
          typescript-eslint:
              patterns: ["@typescript-eslint/"]
          gatsby:
              patterns:
                  - "gatsby"
                  - "gatsby-*"
